### ISSUE TITLE
Buzzer -3dB

### ISSUE THREAD

**Issue by anpar** [Breath4Life/controller#17]

**Comment by cassiersg** [comment]
We have now two pins from the same PWM. (OC0A and OC0B).

Options:
* if current is limited by driving capability of the arduino: enable 1 or 2 pins depending on sound level targetted (a.k.a the brutal way)
* if current is limited by a resistor: put a different resistor in front of each pin, enable one of the two pins.

**Comment by cassiersg** [comment]
Implemented and working on the scope, but not on the device...

**Comment by cassiersg** [comment]
Fixed on the device, but there is a large (~25 dB) difference between low and high level sounds.

**Comment by cassiersg** [comment]
Out of scope: remaining problem is hardware
