### ISSUE TITLE
Specify LCD behaviour when globalState is critical_failure

### ISSUE THREAD

**Issue by anpar** [Breath4Life/controller#22]

**Comment by anpar** [comment]
Currently displays the cause of the critical failure on line 1 (door open, motor error or power error) and "RESTART REQUIRED" on line 2.

TODO: add this to specifications/requirements.

**Comment by matrixreq** [comment]
This issue is linked to Matrix item [SPEC-10](https://breathoflife.matrixreq.com/BreathOfLife/SPEC-10)

**Comment by cassiersg** [comment]
Update:
first line "CRITICAL: [ERROR CODE]"
second line "RESTART REQUIRED"
