### ISSUE TITLE
Open door switch

### ISSUE THREAD

**Issue by anpar** [Breath4Life/controller#27]

**Comment by cassiersg** [comment]
Pin B2 (Digital Pin 51)
Switch open = door closed, switch closed = door closed.
Config as DIO_INPUT_PULLUP

When in RUN state, opening door puts system in CRITICAL_FAILURE state.

-> to improve later.

**Comment by anpar** [comment]
Working fine !

**Comment by cmomin** [comment]
Will be merged soon
