### ISSUE TITLE
Revised LCD display

### ISSUE THREAD

**Issue by anpar** [Breath4Life/controller#35]
- Replace instantaneous pressure by plateau pressure (done on branch p-plateau-calc)
- Display PEEP value: where? With other extra parameters like I:E and Pmax? Pros: easy. Cons: not settable -> confusing user experience.

**Comment by matrixreq** [comment]
This issue is linked to Matrix item [SPEC-10](https://breathoflife.matrixreq.com/BreathOfLife/SPEC-10)
