### ISSUE TITLE
Clarify pressure alarms and threshold

### ISSUE THREAD

**Issue by anpar** [Breath4Life/controller#6]
Discuss with Yves and Olivier.

**Comment by anpar** [comment]
Pressure alarms currently defined on p_peak only ((low-pressure, no-pressure, over-pressure).

Should we have alarms on p_plateau and measured PEEP? To be discussed with health professionals.

**Comment by anpar** [comment]
Answer from Olivier: Pmax settable between 28 and 58cmH2O (2cm less than the overpressure valve, that he hopes will be settable between 30 and 60cmH2O).

No alarm needed on p_plateau and measured PEEP.

**Comment by matrixreq** [comment]
This issue is linked to Matrix item [SPEC-82](https://breathoflife.matrixreq.com/BreathOfLife/SPEC-82)
